[package]
name = "rust_hello"
version = "0.1.0"
authors = ["samreachyan <samreachyan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.12"
regex = "0.1.41"
